/*
Given a string, we have to find out all its subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

Examples: 

Input : abc
Output : a, b, c, ab, bc, ac, abc
*/

#include <iostream>
using namespace std;
void generate(string s)
{
	
}
int main()
{
	string str;
	cout<<"Enter the string:";
	cin>>str;
	cout<<"\nThe subsequences:";
	string output;
	generate(str,output);
}
